##文件保存路径
filePath: ${user.dir}\src\main\static\files\

##数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hslink?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    db-name: hslink
    filters: log4j,wall,mergeStat
    driverClassName: com.mysql.cj.jdbc.Driver
