##端口号
server:
  port: 8048
## mybatis配置
mybatis:
  mapper-locations: classpath*:com/qinxx/hslink/dao/mapping/*.xml
  typeAliasesPackage: com.qinxx.hslink.model
##日志等级
logging:
  level:
    com.qinxx.hslink.dao : debug

spring:
  profiles:
    active: dev
